# Generated by Django 5.2.9 on 2026-01-06 16:18

import coopstack.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="หัวข้อประกาศ"),
                ),
                ("content", models.TextField(verbose_name="เนื้อหา")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=coopstack.models.announcement_file_path,
                        verbose_name="ไฟล์แนบ",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="เผยแพร่ทันที"),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="ปักหมุดข่าวสำคัญ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ประกาศข่าวสาร",
                "verbose_name_plural": "ประกาศข่าวสาร",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ชื่อบริษัท")),
                ("address", models.TextField(blank=True, verbose_name="ที่อยู่")),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ผู้ติดต่อหลัก"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="เบอร์โทรศัพท์"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="อีเมลบริษัท"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="เว็บไซต์")),
                (
                    "teacher_notes",
                    models.TextField(blank=True, verbose_name="บันทึกช่วยจำของอาจารย์"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ข้อมูลบริษัท (Master)",
                "verbose_name_plural": "ข้อมูลบริษัท (Master)",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "ผู้ดูแลระบบ"),
                            ("TEACHER", "อาจารย์นิเทศ"),
                            ("STUDENT", "นักศึกษา"),
                            ("COMPANY", "พี่เลี้ยง/สถานประกอบการ"),
                        ],
                        default="STUDENT",
                        max_length=10,
                        verbose_name="สิทธิ์ผู้ใช้งาน",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ตำแหน่งงาน"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="เบอร์โทรศัพท์ส่วนตัว"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staffs",
                        to="coopstack.companymaster",
                        verbose_name="สังกัดบริษัท",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อมูลพี่เลี้ยง (User)",
                "verbose_name_plural": "ข้อมูลพี่เลี้ยง (User)",
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="ตำแหน่งที่ฝึก"),
                ),
                ("start_date", models.DateField(verbose_name="วันเริ่มฝึกงาน")),
                ("end_date", models.DateField(verbose_name="วันสิ้นสุดฝึกงาน")),
                (
                    "supervisor_name",
                    models.CharField(
                        max_length=100, verbose_name="ชื่อพี่เลี้ยง (หน้างาน)"
                    ),
                ),
                (
                    "supervisor_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="อีเมลพี่เลี้ยง"
                    ),
                ),
                (
                    "supervisor_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="เบอร์โทรพี่เลี้ยง"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รออนุมัติ"),
                            ("APPROVED", "กำลังฝึกงาน"),
                            ("REJECTED", "ไม่อนุมัติ"),
                            ("COMPLETED", "ฝึกงานเสร็จสิ้น"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "teacher_note",
                    models.TextField(blank=True, verbose_name="หมายเหตุจากอาจารย์"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_applications",
                        to="coopstack.companymaster",
                        verbose_name="บริษัท",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบสมัครงาน/การฝึกงาน",
                "verbose_name_plural": "ใบสมัครงาน/การฝึกงาน",
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluator_name",
                    models.CharField(max_length=100, verbose_name="ผู้ประเมิน"),
                ),
                (
                    "part1_score",
                    models.IntegerField(
                        default=0, verbose_name="คะแนนส่วนที่ 1 (วินัย)"
                    ),
                ),
                (
                    "part2_score",
                    models.IntegerField(
                        default=0, verbose_name="คะแนนส่วนที่ 2 (ปฏิบัติงาน)"
                    ),
                ),
                (
                    "part3_score",
                    models.IntegerField(
                        default=0, verbose_name="คะแนนส่วนที่ 3 (ทักษะ)"
                    ),
                ),
                (
                    "total_score",
                    models.IntegerField(default=0, verbose_name="คะแนนรวม"),
                ),
                ("strengths", models.TextField(blank=True, verbose_name="จุดแข็ง")),
                (
                    "weaknesses",
                    models.TextField(blank=True, verbose_name="จุดที่ควรปรับปรุง"),
                ),
                (
                    "suggestion",
                    models.TextField(blank=True, verbose_name="ข้อเสนอแนะเพิ่มเติม"),
                ),
                (
                    "teacher_ack_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รอรับทราบ"),
                            ("ACKNOWLEDGED", "รับทราบแล้ว"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="สถานะการรับทราบผล",
                    ),
                ),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="coopstack.jobapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "ผลการประเมิน",
                "verbose_name_plural": "ผลการประเมิน",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="รหัสนักศึกษา"
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=100, verbose_name="ชื่อจริง"),
                ),
                ("lastname", models.CharField(max_length=100, verbose_name="นามสกุล")),
                ("major", models.CharField(max_length=100, verbose_name="สาขาวิชา")),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="เกรดเฉลี่ย",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="เบอร์โทรศัพท์"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อมูลนักศึกษา",
                "verbose_name_plural": "ข้อมูลนักศึกษา",
            },
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications",
                to="coopstack.student",
            ),
        ),
        migrations.CreateModel(
            name="TrainingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(max_length=200, verbose_name="หัวข้อการอบรม"),
                ),
                ("date", models.DateField(verbose_name="วันที่อบรม")),
                ("hours", models.IntegerField(verbose_name="จำนวนชั่วโมง")),
                (
                    "proof_file",
                    models.FileField(
                        upload_to=coopstack.models.training_proof_path,
                        verbose_name="หลักฐาน (Cert/รูปภาพ)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รอตรวจสอบ"),
                            ("APPROVED", "ผ่าน"),
                            ("REJECTED", "ไม่ผ่าน (แก้ไข)"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "teacher_comment",
                    models.TextField(blank=True, verbose_name="ความเห็นอาจารย์"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainings",
                        to="coopstack.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติการอบรม",
                "verbose_name_plural": "ประวัติการอบรม",
            },
        ),
        migrations.CreateModel(
            name="WeeklyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField(verbose_name="สัปดาห์ที่")),
                ("start_date", models.DateField(verbose_name="วันที่เริ่มของสัปดาห์")),
                ("end_date", models.DateField(verbose_name="วันที่สิ้นสุดของสัปดาห์")),
                ("work_summary", models.TextField(verbose_name="สรุปงานที่ปฏิบัติ")),
                (
                    "problems",
                    models.TextField(blank=True, verbose_name="ปัญหาและอุปสรรค"),
                ),
                (
                    "knowledge_gained",
                    models.TextField(blank=True, verbose_name="สิ่งที่ได้เรียนรู้"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "รอตรวจ"), ("ACKNOWLEDGED", "ตรวจแล้ว")],
                        default="PENDING",
                        max_length=15,
                        verbose_name="สถานะการตรวจ",
                    ),
                ),
                (
                    "teacher_comment",
                    models.TextField(blank=True, verbose_name="ความเห็นอาจารย์"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="coopstack.jobapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายงานประจำสัปดาห์",
                "verbose_name_plural": "รายงานประจำสัปดาห์",
                "ordering": ["week_number"],
                "unique_together": {("job_application", "week_number")},
            },
        ),
    ]
