# Generated by Django 5.2.9 on 2026-01-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coopstack", "0002_jobapplication_accommodation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="location",
            field=models.TextField(
                blank=True,
                help_text="ระบุที่อยู่สถานที่ทำงานจริง หากแตกต่างจากที่อยู่บริษัทหลัก",
                verbose_name="ที่ตั้งสถานประกอบการ (สถานที่จริง)",
            ),
        ),
    ]
