# Generated by Django 5.2.9 on 2026-01-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coopstack", "0003_jobapplication_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklyreport",
            name="end_date",
            field=models.DateField(blank=True, verbose_name="วันที่สิ้นสุดของสัปดาห์"),
        ),
        migrations.AlterField(
            model_name="weeklyreport",
            name="start_date",
            field=models.DateField(blank=True, verbose_name="วันที่เริ่มของสัปดาห์"),
        ),
    ]
