# Generated by Django 5.2.9 on 2026-01-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coopstack", "0004_alter_weeklyreport_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weeklyreport",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="weeklyreport",
            name="start_date",
        ),
    ]
