# Generated by Django 5.2.9 on 2026-01-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coopstack", "0006_weeklyreport_supervisor_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingrecord",
            name="get_hours",
            field=models.PositiveIntegerField(
                default=0, verbose_name="จำนวนชั่วโมงที่ได้รับจริง"
            ),
        ),
        migrations.AlterField(
            model_name="trainingrecord",
            name="hours",
            field=models.IntegerField(verbose_name="จำนวนชั่วโมงที่เคลม"),
        ),
    ]
