# Generated by Django 5.2.9 on 2026-01-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coopstack", "0007_trainingrecord_get_hours_alter_trainingrecord_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="cancel_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="เหตุผลการยกเลิก"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "รออนุมัติ"),
                    ("APPROVED", "กำลังฝึกงาน"),
                    ("REJECTED", "ไม่อนุมัติ"),
                    ("COMPLETED", "ฝึกงานเสร็จสิ้น"),
                    ("CANCELLED", "ยกเลิกโดยนักศึกษา"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="สถานะ",
            ),
        ),
    ]
