# Generated by Django 5.2.9 on 2026-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coopstack", "0008_jobapplication_cancel_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="academic_year",
            field=models.IntegerField(default=2567, verbose_name="ปีการศึกษา"),
        ),
        migrations.AlterUniqueTogether(
            name="companyprofile",
            unique_together={("company", "academic_year")},
        ),
    ]
