# Generated by Django 5.2.9 on 2025-12-20 15:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="ชื่อบริษัท"),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="ที่อยู่หลัก"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ผู้ติดต่อหลัก/HR",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="เบอร์โทรศัพท์",
                    ),
                ),
                (
                    "teacher_comments",
                    models.TextField(
                        blank=True, null=True, verbose_name="ความคิดเห็นอาจารย์"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("STUDENT", "นักศึกษา"),
                            ("TEACHER", "อาจารย์"),
                            ("COMPANY", "ตัวแทนบริษัท"),
                        ],
                        default="STUDENT",
                        max_length=20,
                        verbose_name="บทบาท",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="อีเมล"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CompanyRepresentative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_company_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="representatives",
                        to="coopapi.companymaster",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name_snapshot",
                    models.CharField(
                        max_length=200, verbose_name="ชื่อบริษัท (ขณะสมัคร)"
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="ตำแหน่งงาน"),
                ),
                (
                    "company_location",
                    models.TextField(verbose_name="ที่ตั้งสถานประกอบการ"),
                ),
                (
                    "supervisor_name",
                    models.CharField(max_length=100, verbose_name="ชื่อผู้ดูแล"),
                ),
                (
                    "supervisor_phone",
                    models.CharField(max_length=20, verbose_name="เบอร์โทรผู้ดูแล"),
                ),
                (
                    "accommodation",
                    models.TextField(
                        blank=True, null=True, verbose_name="ที่พักระหว่างฝึก"
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ผู้ติดต่อฉุกเฉิน",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="เบอร์โทรฉุกเฉิน",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        default="2566", max_length=4, verbose_name="ปีการศึกษา"
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        default="1", max_length=1, verbose_name="ภาคเรียน"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="วันเริ่มฝึกงาน")),
                ("end_date", models.DateField(verbose_name="วันสิ้นสุดฝึกงาน")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รออนุมัติ"),
                            ("APPROVED", "อนุมัติ (กำลังฝึกงาน)"),
                            ("REJECTED", "ปฏิเสธ"),
                            ("CANCELLED", "ยกเลิก"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "teacher_note",
                    models.TextField(
                        blank=True, null=True, verbose_name="เหตุผลการปฏิเสธ"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_history",
                        to="coopapi.companymaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.IntegerField(verbose_name="คะแนนรวม")),
                (
                    "evaluation_data",
                    models.JSONField(default=dict, verbose_name="ข้อมูลประเมินละเอียด"),
                ),
                (
                    "strengths",
                    models.TextField(blank=True, null=True, verbose_name="จุดเด่น"),
                ),
                (
                    "weaknesses",
                    models.TextField(
                        blank=True, null=True, verbose_name="ข้อควรปรับปรุง"
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, null=True, verbose_name="ความคิดเห็นเพิ่มเติม"
                    ),
                ),
                (
                    "teacher_ack_status",
                    models.CharField(
                        choices=[("UNREAD", "ยังไม่ตรวจสอบ"), ("READ", "ตรวจสอบแล้ว")],
                        default="UNREAD",
                        max_length=10,
                    ),
                ),
                ("evaluated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations",
                        to="coopapi.companyrepresentative",
                    ),
                ),
                (
                    "job_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="coopapi.jobapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                (
                    "student_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="รหัสนักศึกษา"
                    ),
                ),
                ("major", models.CharField(max_length=100, verbose_name="สาขาวิชา")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications",
                to="coopapi.student",
            ),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coopapi.teacher",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="companyrepresentative",
            name="created_by_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="coopapi.teacher",
            ),
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "target_type",
                    models.CharField(
                        choices=[("ALL", "ทุกคน"), ("INDIVIDUAL", "รายบุคคล")],
                        default="ALL",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coopapi.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_name",
                    models.CharField(max_length=200, verbose_name="หัวข้อการอบรม"),
                ),
                (
                    "proof_file",
                    models.FileField(
                        upload_to="training_proofs/", verbose_name="ไฟล์หลักฐาน"
                    ),
                ),
                ("requested_hours", models.IntegerField(verbose_name="ชั่วโมงที่ขอ")),
                (
                    "approved_hours",
                    models.IntegerField(default=0, verbose_name="ชั่วโมงที่อนุมัติ"),
                ),
                (
                    "teacher_note",
                    models.TextField(
                        blank=True, null=True, verbose_name="หมายเหตุจากอาจารย์"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รอตรวจสอบ"),
                            ("APPROVED", "อนุมัติ"),
                            ("REJECTED", "ปฏิเสธ"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_records",
                        to="coopapi.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField(verbose_name="สัปดาห์ที่")),
                ("work_summary", models.TextField(verbose_name="สรุปงานที่ปฏิบัติ")),
                (
                    "problems_found",
                    models.TextField(blank=True, null=True, verbose_name="ปัญหาที่พบ"),
                ),
                (
                    "knowledge_gained",
                    models.TextField(
                        blank=True, null=True, verbose_name="สิ่งที่ได้เรียนรู้"
                    ),
                ),
                (
                    "supervisor_feedback",
                    models.TextField(
                        blank=True, null=True, verbose_name="ข้อเสนอแนะจากพี่เลี้ยง"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "ส่งแล้ว"),
                            ("ACKNOWLEDGED", "อาจารย์รับทราบ"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="coopapi.jobapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["week_number"],
                "unique_together": {("job_application", "week_number")},
            },
        ),
    ]
