# Generated by Django 5.2.9 on 2025-12-21 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coopapi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="target_type",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="teacher",
        ),
        migrations.AddField(
            model_name="announcement",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="announcements/"),
        ),
        migrations.AddField(
            model_name="announcement",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="announcement",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_documents",
                to="coopapi.teacher",
            ),
        ),
    ]
