# Generated by Django 5.2.9 on 2026-01-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coopstack", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="accommodation",
            field=models.TextField(
                blank=True,
                help_text="ระบุที่อยู่หอพักหรือบ้านพัก",
                verbose_name="ที่พักระหว่างฝึกงาน",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="emergency_contact",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ชื่อผู้ติดต่อฉุกเฉิน"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="emergency_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="เบอร์โทรฉุกเฉิน"
            ),
        ),
    ]
