# Generated by Django 5.2.9 on 2026-01-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coopstack", "0005_remove_weeklyreport_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyreport",
            name="supervisor_feedback",
            field=models.TextField(blank=True, verbose_name="ข้อเสนอแนะจากพี่เลี้ยง"),
        ),
    ]
