# Generated by Django 5.2.9 on 2026-01-11 16:11

import coopstack.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coopstack", "0009_companyprofile_academic_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="academic_year",
            field=models.IntegerField(
                default=coopstack.models.current_academic_year,
                verbose_name="ปีการศึกษา",
            ),
        ),
    ]
