# Generated by Django 5.2.9 on 2026-01-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coopstack", "0011_alter_evaluation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="academic_year",
            field=models.IntegerField(blank=True, null=True, verbose_name="ปีการศึกษา"),
        ),
    ]
