# Generated by Django 5.2.9 on 2026-01-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coopstack", "0012_jobapplication_academic_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="รหัสนักศึกษา"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="คำนำหน้า"
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=100, verbose_name="ชื่อจริง"),
                ),
                ("lastname", models.CharField(max_length=100, verbose_name="นามสกุล")),
                ("major", models.CharField(max_length=100, verbose_name="สาขาวิชา")),
                (
                    "is_registered",
                    models.BooleanField(default=False, verbose_name="ลงทะเบียนแล้ว"),
                ),
            ],
        ),
    ]
